# Generated by Django 4.2.26 on 2025-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_artist_search_count_alter_artist_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
